potager_business:
    resource: "@PotagerBusinessBundle/Controller/"
    type:     annotation
    prefix:   /

potager_back:
    resource: "@PotagerBackBundle/Controller/"
    type:     annotation
    prefix:   /

potager_front:
    resource: "@PotagerFrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@PotagerBusinessBundle/Resources/config/routing/routing.yml"

sonata_user:
    resource: "@PotagerBusinessBundle/Resources/config/routing/admin_security.xml"
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin